### ISSUE TITLE
Pronto doesn't compile in Debian machine (advrmonster)

### ISSUE THREAD

**Issue by cmastalli** [iit-DLSLab/pronto-distro#3]
@mcamurri 

As you know I followed the procedure, in dls wiki, for compilation of pronto. Due to the packages is missing in Debian, I substituted with openjdk-8-jdk. Apart of that, everything is pretty similar to our procedure.

This is the error that I get when I try to compile pronto-distro:

In file included from /home/local/IIT/cmastalli/dls_ws/packages/pronto-distro/pronto/state-estimator/src/gpf/gpf.cpp:1:0:
/home/local/IIT/cmastalli/dls_ws/packages/pronto-distro/pronto/state-estimator/src/gpf/gpf.hpp:49:31: error: redeclaration of ‘template<class LikelihoodInterface> void MavStateEst::gpfMeasurement(MavStateEst::GPFLikelihoodInterface<LikelihoodInterface>_, const MavStateEst::RBIS&, const RBIM&, const VectorXi&, Eigen::VectorXd&, Eigen::MatrixXd&, int, double, bot_lcmgl_t_)’ may not have default arguments [-fpermissive]
     bot_lcmgl_t \* lcmgl = NULL)
                               ^
In file included from /home/local/IIT/cmastalli/dls_ws/packages/pronto-distro/pronto/state-estimator/pod-build/include/mav_state_est/gpf/laser_gpf_lib.hpp:22:0,
                 from /home/local/IIT/cmastalli/dls_ws/packages/pronto-distro/pronto/state-estimator/src/gpf/rbis_gpf_update.hpp:11,
                 from /home/local/IIT/cmastalli/dls_ws/packages/pronto-distro/pronto/state-estimator/src/gpf/rbis_gpf_update.cpp:1:
/home/local/IIT/cmastalli/dls_ws/packages/pronto-distro/pronto/state-estimator/pod-build/include/mav_state_est/gpf/gpf.hpp:49:31: error: redeclaration of ‘template<class LikelihoodInterface> void MavStateEst::gpfMeasurement(MavStateEst::GPFLikelihoodInterface<LikelihoodInterface>_, const MavStateEst::RBIS&, const RBIM&, const VectorXi&, Eigen::VectorXd&, Eigen::MatrixXd&, int, double, bot_lcmgl_t_)’ may not have default arguments [-fpermissive]
     bot_lcmgl_t \* lcmgl = NULL)
                               ^
In file included from /home/local/IIT/cmastalli/dls_ws/packages/pronto-distro/pronto/state-estimator/src/gpf/laser_gpf_lib.hpp:22:0,
                 from /home/local/IIT/cmastalli/dls_ws/packages/pronto-distro/pronto/state-estimator/src/gpf/laser_gpf_lib.cpp:1:
/home/local/IIT/cmastalli/dls_ws/packages/pronto-distro/pronto/state-estimator/pod-build/include/mav_state_est/gpf/gpf.hpp:49:31: error: redeclaration of ‘template<class LikelihoodInterface> void MavStateEst::gpfMeasurement(MavStateEst::GPFLikelihoodInterface<LikelihoodInterface>_, const MavStateEst::RBIS&, const RBIM&, const VectorXi&, Eigen::VectorXd&, Eigen::MatrixXd&, int, double, bot_lcmgl_t_)’ may not have default arguments [-fpermissive]
     bot_lcmgl_t \* lcmgl = NULL)
                               ^
src/gpf/CMakeFiles/gpf-laser-lib.dir/build.make:86: recipe for target 'src/gpf/CMakeFiles/gpf-laser-lib.dir/gpf.cpp.o' failed
make[5]: **\* [src/gpf/CMakeFiles/gpf-laser-lib.dir/gpf.cpp.o] Error 1
make[5]: **\* Waiting for unfinished jobs....
src/gpf/CMakeFiles/gpf-laser-lib.dir/build.make:134: recipe for target 'src/gpf/CMakeFiles/gpf-laser-lib.dir/rbis_gpf_update.cpp.o' failed
make[5]: **\* [src/gpf/CMakeFiles/gpf-laser-lib.dir/rbis_gpf_update.cpp.o] Error 1
src/gpf/CMakeFiles/gpf-laser-lib.dir/build.make:62: recipe for target 'src/gpf/CMakeFiles/gpf-laser-lib.dir/laser_gpf_lib.cpp.o' failed
make[5]: **\* [src/gpf/CMakeFiles/gpf-laser-lib.dir/laser_gpf_lib.cpp.o] Error 1
CMakeFiles/Makefile2:288: recipe for target 'src/gpf/CMakeFiles/gpf-laser-lib.dir/all' failed
make[4]: **\* [src/gpf/CMakeFiles/gpf-laser-lib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: **\* [all] Error 2
Makefile:27: recipe for target 'all' failed
make[2]: **\* [all] Error 2
Makefile:19: recipe for target 'all' failed
make[1]: **\* [all] Error 2
Makefile:22: recipe for target 'all' failed
make: **\* [all] Error 2

Carlos

**Comment by jbcolme** [comment]
Do you know why Ricardo installed Debian instead of ubuntu?

**Comment by cmastalli** [comment]
No idea but probably there are historical reason. Remember that he didn't buy the monster for ROS stuff.
